[package]
name = "en-croissant"
version = "0.1.2"
description = "A Modern Chess Database"
authors = ["Francisco Salgueiro <fgcdbs@gmail.com>"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
tauri-plugin-oauth = { path = "./src/tauri-plugin-oauth" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["api-all", "updater"] }
zip = "0.6.2"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
futures-util = "0.3.24"
reqwest = { version = "0.11.6", features = ["stream", "blocking", "json"] }
shakmaty = "0.23.0"
pgn-reader = "0.22.0"
csv = "1.1.6"
lazy_static = "1.4.0"
btoi = "0.4.2"
rusqlite = { version = "0.28.0", features = ["bundled"] }
bzip2 = "0.4.3"
zstd = "0.12.1"
serde_with = "2.1.0"
diesel = { version = "2.0.2", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "r2d2"] }
rayon = "1.6.1"
chrono = "0.4.24"
hex = "0.4.3"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.test]
opt-level = 3
